# -*- coding: utf-8 -*-
"""feedback.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1giADIXzyZq63PpvC9M8QoVrmmHmAfphj
"""

# csv 파일 새로 올려주시면 반영해서 수정할 예정
import pandas as pd
import numpy as np

import pandas as pd
import io

# 파일 로드 (data2.csv)
try:
    df = pd.read_csv('data2.csv')
except FileNotFoundError:
    print("파일을 찾을 수 없습니다. 'data2.csv' 파일 경로를 확인해주세요.")
    exit()

# 'action' 컬럼의 문자열 값을 정수 리스트로 변환
# 쉼표로 구분된 문자열을 파싱하고 정수로 변환합니다.
df['action_list'] = df['action'].apply(lambda x: [int(i) for i in str(x).split(',')])

# 결과를 담을 빈 리스트 초기화
explicit_feedback_list = []
implicit_feedback_list = []

# 데이터프레임을 행 단위로 순회
for index, row in df.iterrows():
    user_id = row['user_id']
    step = row['step']
    reward = row['reward']
    actions = row['action_list']

    # 해당 행의 추천 아이템 개수 (응답 컬럼셋의 인덱스 상한)
    num_actions = len(actions)

    for i, item_id in enumerate(actions):
        # i는 0부터 num_actions - 1까지의 인덱스로, resp_i 컬럼셋에 대응됩니다.

        # --- 1. Explicit Feedback 추출 ---
        # Explicit: user_id, item_id, step, reward
        # reward는 해당 user/step의 모든 action item에 동일하게 적용됩니다.
        explicit_feedback_list.append({
            'user_id': user_id,
            'item_id': item_id,
            'step': step,
            'reward': reward
        })

        # --- 2. Implicit Feedback 추출 ---
        # Implicit: user_id, item_id, step, response

        prefix = f'resp_{i}_'

        # 응답 컬럼이 있는지 확인하고 값을 가져옵니다.
        # 컬럼이 없을 경우 (예: action 개수보다 응답 컬럼셋이 부족한 경우) 기본값 0을 사용
        clicked = row.get(prefix + 'click', 0)
        watched = row.get(prefix + 'watch', 0)
        liked = row.get(prefix + 'liked', 0)

        # response 판단: click, watch, liked 중 하나라도 1이면 1, 아니면 0
        # 논리합(OR) 연산을 사용하여 판단
        response = 1 if (clicked == 1 or watched == 1 or liked == 1) else 0

        implicit_feedback_list.append({
            'user_id': user_id,
            'item_id': item_id,
            'step': step,
            'response': response
        })

# 결과 데이터프레임 생성
explicit_df = pd.DataFrame(explicit_feedback_list)
implicit_df = pd.DataFrame(implicit_feedback_list)

# 결과 확인
print("--- Explicit Feedback (일부) ---")
print(explicit_df.head(10))
print(f"\n총 Explicit Feedback 수: {len(explicit_df)}")
print("\n--- Implicit Feedback (일부) ---")
print(implicit_df.head(10))
print(f"\n총 Implicit Feedback 수: {len(implicit_df)}")